### ISSUE TITLE
"pip3 install crazydiskmark" is giving version error

### ISSUE THREAD

**Issue by ruzickap** [fredcox/crazydiskmark#2]
I'm getting the version error wen running ""pip3 install":

```bash
$ pip3 install crazydiskmark
Collecting crazydiskmark
  ERROR: Could not find a version that satisfies the requirement crazydiskmark (from versions: none)
ERROR: No matching distribution found for crazydiskmark
```

Thanks for looking at it.

**Comment by fredcox** [comment]
> ```shell
> Could not find a version that satisfies the requirement
> ```

Can you try 

`pip3 install crazydiskmark==0.2.20`

and give output here? 

Thank u.

**Comment by ruzickap** [comment]
Seems like problem is somewhere on my side.
If I run it inside container it's working fine.

Thanks for helping...

Closing...
