### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by LibraryofV** [fredcox/crazydiskmark#5]
Hey, what's up?

Your app looks nice but the following error occurs when I try to install it using pip3:

```
elementary@elementary:~$ pip3 install crazydiskmark
Collecting crazydiskmark
  Could not find a version that satisfies the requirement crazydiskmark (from versions: )
No matching distribution found for crazydiskmark
```
Note that I have python 3.85, pip3 is installed, I've done a sudo apt update, and I have added $ export PATH=$PATH:~/.local/bin as per your instructions.

Any tips?

Cheers,
V

**Comment by fredcox** [comment]
> Hey, what's up?
> 
> Your app looks nice but the following error occurs when I try to install it using pip3:
> 
> ```
> elementary@elementary:~$ pip3 install crazydiskmark
> Collecting crazydiskmark
>   Could not find a version that satisfies the requirement crazydiskmark (from versions: )
> No matching distribution found for crazydiskmark
> ```
> 
> Note that I have python 3.85, pip3 is installed, I've done a sudo apt update, and I have added $ export PATH=$PATH:~/.local/bin as per your instructions.
> 
> Any tips?
> 
> Cheers,
> V

Hi, sorry but i not see now your issue. Ok. This message "Could not find a version that satisfies the requirement c..." is classical. It is because the python3 instal in yout system not 3.8 or latest,  or maybe any wrong with your python 3 install. This is classical message by pip.
