### ISSUE TITLE
Using crazydiskmark in a HDD

### ISSUE THREAD

**Issue by sagudeloo** [fredcox/crazydiskmark#7]
I have a question, Why you don't recommend to use crazydiskmark in an HDD? What could happend if I execute it in an HDD?

**Comment by fredcox** [comment]
> I have a question, Why you don't recommend to use crazydiskmark in an HDD? What could happend if I execute it in an HDD?

Hi, @sagudeloo , Crazy DiskMark work fine with mechanicals HDD, but the benchmark in this kind of device is slowly, because the read/write latency is high. I will remove this warning later. 

Thank you for using Crazy DiskMark.
